### ISSUE TITLE
Problem with installing class_sz

### ISSUE THREAD

**Issue by ibitoye** [borisbolliet/class_sz#5]
I cloned class_sz code on my computer and installed it.

To test is this works I do

from classy_sz import Class

But it returned this error message:

**---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-8e13adabfad5> in <module>()
----> 1 from classy_sz import Class

ImportError: /home/ibitoye/test/local/lib/python2.7/site-packages/classy_sz.so: undefined symbol: fftw_plan_dft_1d**

Can you please assist me to resolve this?

**Comment by borisbolliet** [comment]
Hi @ibitoye,

sorry I am seeing this just now. The issue seems to just be that you haven't specified the FFTW library paths properly. 


Do you still have the issue?

Boris

**Comment by ibitoye** [comment]
Dear Boris,

I got it resolved already.

Thank you so much for the reply.

Best,
Ayodeji

**Comment by borisbolliet** [comment]
Great Thank you!
